### ISSUE TITLE
Present loading information

### ISSUE THREAD

**Issue by eddieantonio** [ReadAlongs/Web-Component#10]
The component should notify the user when:
 - the media is loading (controls disabled)
 - the media has loaded and is ready (controls enabled)
 - the media failed to load (controls disabled, error message)

This came from my mistake:

> THAT SAID, I think the component could be a bit more resilient about this kind of error and handle what happens when loading fails for any reason.

_Originally posted by @eddieantonio in https://github.com/roedoejet/ReadAlong-Web-Component/issues/9#issuecomment-836789607_

**Comment by deltork** [comment]
see #29
