### ISSUE TITLE
Add CORS headers to development server

### ISSUE THREAD

**Issue by dhdaines** [ReadAlongs/Web-Component#73]
Actually the only place this is really needed is for `serve-test-data` in `web-component`, and all we need to do is add `--cors` to the command-line in `packages/web-component/package.json`.

Waiting for the merge of studio-web to add this :)

**Comment by joanise** [comment]
If we add `--cors` to `packages/web-component/package.json`, will it break things if someone tries to run it with an old Studio sandbox? I was going to have `PRODUCTION= DEVELOPMENT=1 uvicorn` in that `serve-web-api` script so it works before and after...

**Comment by dhdaines** [comment]
I don't think it should break anything, it works the same as before (and it's for development only in any case) but it means we don't need the CORS extension anymore.

**Comment by dhdaines** [comment]
fixed in #75
