### ISSUE TITLE
web-component server doesn't die on Control-C

### ISSUE THREAD

**Issue by dhdaines** [ReadAlongs/Web-Component#74]
This is, actually, not our fault, but I'm adding an issue here because it's a longstanding Nx bug that the maintainers claim is fixed, but is clearly not: https://github.com/nrwl/nx/issues/3348

**Comment by joanise** [comment]
Not that this is going to help you or make you any happier, but I don't have this problem on Windows. My node servers reliably get killed when I hit Ctrl-C. However, I believe Aidan also has the problem, so it appears to be a *nix issue.

**Comment by roedoejet** [comment]
recommendation is unfortunately just to `killall node` between serves until Nx fixes it...

**Comment by dvag-lukas-rybacki** [comment]
Same issue here with version `v21.0.0`
